### DS201 Capstone 1
#### By Abby and Lilly

In [1]:
!wget "https://www.fhfa.gov/hpi/download/monthly/hpi_master.csv"

--2026-09-17 20:47:24--  https://www.fhfa.gov/hpi/download/monthly/hpi_master.csv
Resolving www.fhfa.gov (www.fhfa.gov)... 54.92.167.213
Connecting to www.fhfa.gov (www.fhfa.gov)|54.92.167.213|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 17154972 (16M) [text/csv]
Saving to: ‘hpi_master.csv’

hpi_master.csv      100%[===================>]  16.36M  28.5MB/s    in 0.6s

2026-09-17 20:47:25 (28.5 MB/s) - ‘hpi_master.csv’ saved [17154972/17154972]

### 1. Understanding the Data

### 2. Exploratory Data Analysis

In [9]:
import pandas as pd
hpi = pd.read_csv('hpi_master.csv')

# summary statistics for the numeric data
hpi.describe()

/tmp/ipykernel_2092/1264052065.py:2: DtypeWarning: Columns (11) have mixed types. Specify dtype option on import or set low_memory=False.
  hpi = pd.read_csv('hpi_master.csv')

                  yr         period      index_nsa      index_sa       rstderr
count  186011.000000  186011.000000  186011.000000  96114.000000  58220.000000
mean     2006.159926       2.581014     199.962128    216.670407      2.673249
std        12.004355       1.358702     116.125443    113.512712      2.222155
min      1975.000000       1.000000      18.600000     72.780000      0.000000
25%      1997.000000       2.000000     119.610000    137.290000      1.060000
50%      2007.000000       3.000000     172.130000    187.210000      2.050000
75%      2016.000000       4.000000     241.380000    258.337500      3.600000
max      2026.000000      12.000000    1326.940000   1043.200000     15.750000

In [8]:
# find missing values in every column
hpi.isna().sum()

hpi_type           0
hpi_flavor         0
frequency          0
level              0
place_name         0
place_id           0
yr                 0
period             0
index_nsa          0
index_sa       89897
rstderr       127791
note          127791
dtype: int64